apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-tasks
  namespace: tasks
spec:
  selector:
    matchLabels:
      app: frontend-tasks
  template:
    metadata:
      labels:
        app: frontend-tasks
    spec:
      containers:
      - name: frontend-tasks
        image: yoandevelop/frontend-tasks-react:v1
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-tasks-svc
  namespace: tasks
spec:
  type: NodePort
  selector:
    app: frontend-tasks
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    

