# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React-Tasks-Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
  
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm run build --if-present
  
    - name: Set up Docker Build to Image
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to Registry
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: yoandevelop/frontend-tasks-react:${{ github.sha }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'yoandevelop/frontend-tasks-react:${{ github.sha }}'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
      
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Try the cluster!
        run: kubectl get pods -A

      - name: Deploy to minikube
        run: |
          kubectl create ns tasks
          kubectl config set-context --current --namespace=tasks
          kubectl apply -R -f ./deploy-k8s/
          kubectl wait --for=condition=ready pod -l app=frontend-tasks --timeout=120s
          kubectl get all

      - name: Test service URLs
        run: |
          minikube service list
          minikube service frontend-tasks-svc -n tasks --url
          echo -n "------------------opening the service-----------------------"
          curl $(minikube service frontend-tasks-svc -n tasks --url)/version

